### ISSUE TITLE
What does the Zest stats coverage "percentage of map" actually mean?

### ISSUE THREAD

**Issue by CryoCodec** [rohanpadhye/JQF#106]
Hi there, 
I have been using JQF+Zest in a recent project, working out fine so far. You did a great Job on it! However I have a hard time understanding what the "percentage of map" in the Zest stats actually stands for. 

Given the following Zest stats output: 

```
... 
Queue size:           12 (2 favored last cycle)
Current parent input: 0 (favored) {665/980 mutations}
Execution speed:      35/sec now | 112/sec overall
Total coverage:       1.316 branches (2,01% of map)
Valid coverage:       1.308 branches (2,00% of map)
```

Up to now I've assumed, the coverage counts distinct visited branches - usually referred to as branch coverage. However when using randomly selected inputs generated during the fuzzing and applying them to check the coverage with Intellij, neither the statement-coverage nor the branch-coverage are even close to the 2%. Apparently both values are way higher in Intellij. 

This observation is surprising for me and I guess, I got something wrong. Could you please clarify, what the percentage actually means?

**Comment by rohanpadhye** [comment]
Thanks for your question! I guess this should be documented somewhere, or removed completely. 

Internally, Zest uses a fixed-size hashtable as an `int[]` instead of `java.util.HashMap` to collect coverage during test execution. This is because `HashMap` is incredibly slow compared to array accesses, and coverage information is collected at *every branch* in test execution, so performance matters a lot. With that said, the fixed sized array doesn't automatically resize to increase capacity the way `HashMap` does. The `% of map` in the status screen above shows the percentage of the array that is filled with entries.  If this value goes above say 60-70%, then there are likely many hash collisions and the size of this array should be increased and a new fuzzing session should be started (although this feature has not yet been added; another todo). By default, the array size is about 2^16 entries, which is small enough to fit within L3 cache of most modern processors throughout test execution, while being large enough to keep hash collisions low for most targets we have fuzzed so far. This design choice is largely inherited from AFL.

Zest cannot compute the % coverage the way IntelliJ does, because it does not know the total sum of all your application classes. So Zest does not know what 100% would mean. Further, 100% code coverage is almost impossible from a single fuzzing entry point for most applications, so Zest just reports the absolute number of branches rather than % coverage.

Hope this helps. I'll keep this issue open as a reminder to me to either document this information, remove the confusing detail, and/or allow users to customize the size of the array map.
