### ISSUE TITLE
when does the method "handleEvent" in Guidance class called?

### ISSUE THREAD

**Issue by Anderson-Xia** [rohanpadhye/JQF#116]
Hello author!
  I tried to debug jqf with ideal but during the test the coverage is always zero. And I found the method "handleEvent" is never called in that case. Could you please tell me how could this happen? 
  By the way, the project can work and calculate coverage when I use terminal.

**Comment by rohanpadhye** [comment]
JQF needs to be able to instrument classes as they are being loaded by the JVM in order to collect coverage feedback. The [command-line runner](https://github.com/rohanpadhye/JQF/blob/jqf-1.6/scripts/jqf-driver.sh) uses a javaagent and special bootclasspath, whereas the Maven plugin uses a custom [instrumenting class loader](https://github.com/rohanpadhye/JQF/blob/jqf-1.6/maven-plugin/src/main/java/edu/berkeley/cs/jqf/plugin/FuzzGoal.java#L298-L300) before [running guided fuzzing](https://github.com/rohanpadhye/JQF/blob/jqf-1.6/maven-plugin/src/main/java/edu/berkeley/cs/jqf/plugin/FuzzGoal.java#L329).

If you want to collect coverage when running from IDEA, you will have to either set javaagend/bootclasspath or customize the classloader. I don't know the specifics of IntelliJ settings but that's a direction to consider.

Hope this helps.

**Comment by carolemieux** [comment]
To follow up on that; to run a particular test in IDEA with coverage enabled, you can go to `Edit Configurations`, choose the test you want to run, and add the VM options from the [command-line runner](https://github.com/rohanpadhye/JQF/blob/jqf-1.6/scripts/jqf-driver.sh) to the configurations. Those options are
```
-ea -Xbootclasspath/a:"$INST_CLASSPATH"  ${JAVAAGENT}  -Djanala.conf="${SCRIPT_DIR}/janala.conf"  -cp "${FUZZ_CLASSPATH}:${CLASSPATH}"
```
with the environment variables defined. Refer to the [command-line runner](https://github.com/rohanpadhye/JQF/blob/jqf-1.6/scripts/jqf-driver.sh) for how to set those variables appropriately.

**Comment by Anderson-Xia** [comment]
Thank you for replying. I'll have a try.  : )
