### ISSUE TITLE
AFL

### ISSUE THREAD

**Issue by zheng-yan-max** [rohanpadhye/JQF#119]
Hi author, I was wondering how to use MVN to run the AFL tool. I used the Javac from your tutorial to compile the file, but I got some errors (the dependency is confirmed to be ok).

**Comment by rohanpadhye** [comment]
The Maven plugin cannot be used to run AFL. You can run the Zest engine with the JQF Maven Plugin (plus some others).

To run AFL, you will need to run the command-line scripts as shown in this [tutorial](https://github.com/rohanpadhye/jqf/wiki/Fuzzing-with-AFL). The reason is that for AFL to work out-of-the-box we have to trick AFL into thinking that it is talking to an instrumented binary whereas we actually have a proxy that sits between AFL and the JVM and relays coverage information. This setup does not integrate with the Maven testing workflow.
