### ISSUE TITLE
Unable to communicate with fork server (OOM?)

### ISSUE THREAD

**Issue by DmitryJustDmitry** [rohanpadhye/JQF#140]
Hi.
Using the last version of jqf after successful build and start (with afl++ afl --branch 2.25) i stuck into:

user@user-VirtualBox:~/work/Java/target$ ../jqf/bin/jqf-afl-fuzz  -m 30000000 -t 1000000  -i ../test/in -o ../test/out test1 testRead
Performing pilot run....  Pilot run success! Launching AFL now...
afl-fuzz++2.52c by <lcamtuf@google.com>, schedules by <marcel.boehme@acm.org>
[+] Using exploration-based constant power schedule (EXPLORE)
[+] You have 2 CPU cores and 2 runnable tasks (utilization: 100%).
[!] WARNING: Not binding to a CPU core (AFL_NO_AFFINITY set).
[*] Checking core_pattern...
[*] Setting up output directories...
[+] Output directory exists but deemed OK to reuse.
[*] Deleting old session data...
[+] Output dir cleanup successful.
[*] Scanning '../test/in'...
[+] No auto-generated dictionary tokens to reuse.
[*] Creating hard links for all input files...
[*] Validating target binary...
[*] Attempting dry run with 'id:000000,orig:1'...
[*] Spinning up the fork server...
[+] All right - fork server is up.

[-] PROGRAM ABORT : Unable to communicate with fork server (OOM?)
         Location : run_target(), afl-fuzz.c:2441

When i change jqf to the March commit (git checkout d41d87d6899ee0b1ece05763c376bfcebc8f095a for example) and rerun setup.sh everything works fine. 

Memory and timeout could be set to none - it does not mater.

Attaching my simple test1.java for reproduction.

[test1.java.txt](https://github.com/rohanpadhye/JQF/files/6594111/test1.java.txt)

**Comment by rohanpadhye** [comment]
Thank you! I confirm that I can reproduce this and also that the issue did not exist in the March commit. I appreciate the detailed report. 

On further bisection, it seems the regression was introduced in commit 65a9f09ed due to the [relaxing of entry point matching in ThreadTracer](https://github.com/rohanpadhye/JQF/commit/65a9f09ed9c59147b168b3b8fd05a347b124421c#diff-2037e85081a1437b24e891e039daa21e4d4a5dc17f2dd85d59ade0fbefa525f8L192). The AFL error goes away if the environment variable `JVM_OPTS` is set to include the option `-Djqf.tracing.MATCH_CALLEE_NAMES=true`. While this is a workaround, it should not be necessary (and will likely reduce fuzzing speed). I will try to find a permanent fix today that allows the JQF-AFL integration to work by default.

**Comment by rohanpadhye** [comment]
Pushed a fix. Please reopen if this issue persists even after commit 8608101.
