### ISSUE TITLE
Clarify versioning schema

### ISSUE THREAD

**Issue by sdruskat** [rohanpadhye/JQF#150]
Hi, and thanks for a great project.

I'm wondering what the versioning schema for this project is. Seeing the tags (containing `1.8`, etc.), I was assuming [SemVer](https://semver.org), but I see that the API has changed between minor increments (e.g., the newly added constructor arguments in `ZestGuidance`)? Or am I mixing up things?

FWIW, I think that following semantic versioning would be great, and make it easier for forks to contribute back to the upstream.

**Comment by rohanpadhye** [comment]
Hello! Thanks for the comment. Although we didn't have a formal policy at the outset, I've been trying to follow semantic versioning to ensure backward compatibility between minor versions as much as possible. 

The breaking constructor API in ZestGuidance is certainly a bug. I probably didn't review #145 thoroughly enough. I see that it is only in the snapshot version and not released yet, so I'll start an issue to get that fixed before 1.8.  Thanks for pointing it out! Do let me know if you've noticed any other API else breaking.

**Comment by sdruskat** [comment]
> Hello! Thanks for the comment. Although we didn't have a formal policy at the outset, I've been trying to follow semantic versioning to ensure backward compatibility between minor versions as much as possible.

:+1: 

> The breaking constructor API in ZestGuidance is certainly a bug. I probably didn't review #145 thoroughly enough. I see that it is only in the snapshot version and not released yet, so I'll start an issue to get that fixed before 1.8. Thanks for pointing it out! Do let me know if you've noticed any other API else breaking.

Thanks for the speedy fix, that's great!

My student project group is currently preparing a PR with some experimental speed-ups for Zest, and one thing we use is the `Input.valid` field, which has also been removed in https://github.com/rohanpadhye/JQF/commit/03720a58b1a2fc5aba693bc3a5f6effd867da8ea (https://github.com/rohanpadhye/JQF/commit/03720a58b1a2fc5aba693bc3a5f6effd867da8ea#diff-58de5e33ffaf2151b17488abec4577d737a50ff8dc848906af4ca1634f6a0d97L1036-L1040). Seeing that it's package private, I'm not sure that it's strictly speaking API, but keeping (or reintroducing) it would certainly avoid duplicate implementations of `Input` and its subclasses.

**Comment by rohanpadhye** [comment]
Yes, I actually removed `valid` in order to make `ZestGuidance` _more_ extensible, without having to rely on non-public fields. In fact, `Input.valid` was not really used for anything even before  03720a5. The information of whether an input is valid or not is usually known in `handleResult()`, and I recently added a protected method [`checkSavingCriteria(result)`](https://github.com/rohanpadhye/JQF/blob/03720a58b1a2fc5aba693bc3a5f6effd867da8ea/fuzz/src/main/java/edu/berkeley/cs/jqf/fuzz/ei/ZestGuidance.java#L689) which should allow subclasses to handle custom input-saving logic. This hasn't been fully documented yet, but that's where I was going with this since I have more than one set of use cases for extending Zest.

 If you think associating `Input` objects with validity is necessary for some feature you are planning to send a PR for, please reintroduce the field and I'd be fine with adding it back, perhaps with a public getter method. Now that I think of it, an even better API would be an `Input.getResult()` method that can have the accurate result for an input, or `null` if it hasn't been executed yet. I'm just a bit wary of a boolean field right now because `Input.valid == false` does not imply that can input is invalid if it hasn't yet been run on the test target.
