### ISSUE TITLE
NoSuchMethodError exception

### ISSUE THREAD

**Issue by ST-Saint** [rohanpadhye/JQF#154]
Thanks for your great work first.

I am trying to implement fuzz testing(using jqf-alf-fuzz) in a project which only support compile with java 8, and I noticed that it would occasionally throw an exception:

```
java.lang.NoSuchMethodError: java.nio.ByteBuffer.position(I)Ljava/nio/ByteBuffer;
```

I assumed that should be a problem caused by compiling with java 9+ and execute with java 8. However I did not install openjdk except openjdk-8. Thus I am wondering if JQF is rewriting the *.class files with java 9+? and how could I get rid of this?

Thanks again.

**Comment by ST-Saint** [comment]
I noticed that you are using ASM8 to instrument. I change it to ASM5 and it should work now.

**Comment by rohanpadhye** [comment]
This is not an issue with compiling with different JDK versions, it is related to the methods in the JDK 8/9 library. The ByteBuffer class got new methods in Java 9, such as [position()](https://docs.oracle.com/javase/9/docs/api/java/nio/ByteBuffer.html#position-int-) (not available in [JDK 8's ByteBuffer](https://docs.oracle.com/javase/8/docs/api/java/nio/ByteBuffer.html)).

JQF now expects at least Java 9 to be available (it's been available since September 2017, which is four years now).

Note that you can compile your target program with Java 8; that's no problem. You just need Java 9+ to run JQF.
