### ISSUE TITLE
ZestGuidance does not save inputs when using inside IDEA 

### ISSUE THREAD

**Issue by QRXqrx** [rohanpadhye/JQF#166]
Hi there,
First of all thank you for the contributions you made to JQF. The framework is very nice and the documents are really helpful. 

I recently bump into a problem that when I try to start guided fuzzing through a junit test using ZestGuidance, it turns out that the generated inputs are always not saved and the coverage didn't improve either. It seems the protected method ``saveCurrentInput`` is never invoked. The example I run is ``CalendarLogic`` and ``CalendarTest``. I built these example according to wikis and it works fine with mvn (``mvn jqf:fuzz``) and shell scripts. 

Specifically, I used the following code to drive guided fuzzing:
```
    @Test
    public void testCalendarStdZest() throws IOException, ClassNotFoundException {
        // Trial fuzzing
        String testClassName = CalendarTest.class.getName();
        String testMethodName = "testLeapYear";
        String outputDirName = "target/fuzz-results";
        File outputDirectory = new File(outputDirName);

        String title = testClassName+"#"+testMethodName;
        ZestGuidance guidance = new StdPrintZest(title, null, outputDirectory);

        Result res = GuidedFuzzing.run(testClassName, testMethodName, guidance, System.out);
        if (Boolean.getBoolean("jqf.logCoverage")) {
            System.out.println(String.format("Covered %d edges.",
                    guidance.getTotalCoverage().getNonZeroCount()));
        }
        if (Boolean.getBoolean("jqf.ei.EXIT_ON_CRASH") && !res.wasSuccessful()) {
            System.exit(3);
        }
    }
```
Note that by ``StdPrintZest`` I override ``displayStats`` method to show fuzzing process in standard output as ``System.console()`` always return ``null`` inside IDEA. 
The outputs I got are always like:
```
Test name:            xxx.CalendarTest#testLeapYear
[DEBUG]Not execute saveCurrentInput
Results directory:    xxxx
Elapsed time:         4s (no time limit)
Number of executions: 76,196 (no trial limit)
Valid inputs:         46 (0.06%)
Cycles completed:     0
Unique failures:      1
Queue size:           0 (0 favored last cycle)
Current parent input: <seed>
Execution speed:      39,963/sec now | 17,215/sec overall
Total coverage:       0 branches (0.00% of map)
Valid coverage:       0 branches (0.00% of map)

Semantic Fuzzing with Zest
--------------------------

Test name:           xxx.CalendarTest#testLeapYear
[DEBUG]Not execute saveCurrentInput
Results directory:    xxxx
Elapsed time:         4s (no time limit)
Number of executions: 90,966 (no trial limit)
Valid inputs:         54 (0.06%)
Cycles completed:     0
Unique failures:      1
Queue size:           0 (0 favored last cycle)
Current parent input: <seed>
Execution speed:      49,233/sec now | 19,247/sec overall
Total coverage:       0 branches (0.00% of map)
Valid coverage:       0 branches (0.00% of map)

...
```

It is obvious that the parent input is always ''<seed>'' as no input has been saved. Is there any reason why Zest cannot be used inside an IDE or drived by a unit test? Thank u in advance :-) .

**Comment by rohanpadhye** [comment]
Hello. Glad to learn that you have found JQF to be useful.

For your issue, it looks like there is no coverage being collected because `CalendarTest` is a class that's already loaded on this line:

>      String testClassName = CalendarTest.class.getName();

In order to collect coverage, JQF needs to be able to load application classes using its own classloader. That way, it can instrument class files to track execution of various instructions. So, you cannot have JQF or the classes that drive fuzzing (that is, anything that calls `GuidedFuzzing.run()`) and the application classes (e.g. `CalendarTest`) in the same classpath. 

It's possible to do what you are attempting though, as long as you separate your target classes in a separate module/project from the code that's programatically invoking the fuzzer.

For an example, see the [integration test in JQF](https://github.com/rohanpadhye/JQF/blob/master/integration-tests/src/test/java/edu/berkeley/cs/jqf/fuzz/guidance/ZestGuidanceIT.java). The target application class (`PatriciaTrie`) is in `jqf-examples`, which is in a separate module from `jqf-integration-tests`. The test module picks up JARs from the examples module using an [explicit classpath](https://github.com/rohanpadhye/JQF/blob/5325952a053625057fb2594e2f6aa1c9ac3ac098/integration-tests/src/test/java/edu/berkeley/cs/jqf/fuzz/guidance/AbstractGuidanceIT.java#L29-L38). That [classloader is then used to run `GuidedFuzzing`](https://github.com/rohanpadhye/JQF/blob/5325952a053625057fb2594e2f6aa1c9ac3ac098/integration-tests/src/test/java/edu/berkeley/cs/jqf/fuzz/guidance/ZestGuidanceIT.java#L62).

**Comment by QRXqrx** [comment]
Hey, thank u for your quick replying!  I have tried the examples in ``jqf-integration-tests`` and it does resolve my problem. Thank you very much.

By the way, I'm curious about the instrumenting used by JQF. The class loader used in in ``AbstractGuidanceIT`` is ``InstrumentingClassLoader``. I have not investigated this type in deep but does it mean JQF uses static instrument (instrumenting in advance) to gather coverage rather than dynamic instrument (instrumenting on-the-fly)?

**Comment by rohanpadhye** [comment]
Glad that helped.

Instrumenting classes as they are loaded is equivalent to on-the-fly
instrumentation. The JVM loads classes lazily and dynamically only when
they are first referenced by some executing instruction. So, a class won't
be loaded/instrumented if it is not used in an application.

**Comment by QRXqrx** [comment]
Thanks a lot. I will close this issue.
