### ISSUE TITLE
Overriden methods not instrumented by JQF

### ISSUE THREAD

**Issue by cniddodi** [rohanpadhye/JQF#167]
When fuzzing an `@Override` method using JQF, the coverage reported by JQF does not include the code in the method - `A.foo` in the example below.
However, when fuzzing a non-overridden replica of the above method (i.e, everything else is exactly the same except that this method is not an `@Override` method) in the same class, the reported coverage does include all the code within the method - `A.foo1` in the example below.
It looks like JQF does not instrument `@Override` methods.

```
public interface B {
    public int foo(int i);
}

public class A implements B {

    @Override
    public int foo(int i) { 
	
	int j;
	
	if(i%2==0)
		j = i*2;
	else if(i%3==0)
		j = i/3;
	else
		j = i*4;
	return j;

    }
   
    public int foo1(int i) { 
	
	int j;
	
	if(i%2==0)
		j = i*2;
	else if(i%3==0)
		j = i/3;
	else
		j = i*4;
	return j;

    }
}
```

**Comment by rohanpadhye** [comment]
Thanks for the report! This is interesting. I'll come back to this issue
after the year-end holidays.

**Comment by rohanpadhye** [comment]
I tried replicating your issue but was not successful. I'm using branch [`jqf-issue-167` in the `jqf-zest-example` repo](https://github.com/rohanpadhye/jqf-zest-example/tree/jqf-issue-167).

Steps to set up:
```
git clone https://github.com/rohanpadhye/jqf-zest-example.git --branch jqf-issue-167
cd jqf-zest-example
mvn test-compile
```

Then fuzz both the test methods:
```
mvn jqf:fuzz -Dclass=examples.OverrideTest -Dmethod=testFoo -DrandomSeed=42 -Dtrials=1000 
mvn jqf:fuzz -Dclass=examples.OverrideTest -Dmethod=testFoo1 -DrandomSeed=42 -Dtrials=1000
```

In both cases, I see 7 branches being covered, as expected. There is no difference between the overridden method and the non-overriden method.

Is there some additional context required to reproduce the issue? Feel free to file a PR on that branch to demonstrate the issue so that I can replicate it.

**Comment by cniddodi** [comment]
We ran into this issue while using JQF version 1.7 with a larger Gradle based java project that has SQLite database and other dependencies (not in the small example posted to explain the concept). 

We were able to resolve the issue by making the method being fuzzed a non-overridden one. We did not make any other changes.

So, the issue looks to be related to the `override` feature.

**Comment by rohanpadhye** [comment]
Hmm. Without an example to reproduce it, there is no way for me to debug it. It could be related to something else (e.g. the superclass not being instrumented). Thanks for the report, though; I'll keep it in mind if it comes up again.
