### ISSUE TITLE
Throws IllegalStateException when calling readAllBytes of the return value of ZestGuidance.getInput.

### ISSUE THREAD

**Issue by QRXqrx** [rohanpadhye/JQF#170]
Hi there,
     I have a requirement to make copies of the generated inputs. To this end, I firstly consolidate the bytes of the generated input stream by calling ``readAllBytes()``, which is a method supplied in java ``InputStream``, and then construct ``ByteArrayInputStream`` as copies of the input. However, it always turns out to throw a ``IllegalStateException`` when calling ``readAllBytes()``, which is coded at ``ZestGuidance$LinearInput#getOrGenerateFresh``.  I made the following modification to ``FuzzStatement`` to trigger this issue:
```
.... (Keep other code the same.)
InputStream input = guidance.getInput();
\\ Consolidate bytes
byte[] bytes = input.readAllBytes();   
\\ Rebuild a stream
StreamBackedRandom randomFile = new StreamBackedRandom(new ByteArrayInputStream(bytes), Long.BYTES);    
SourceOfRandomness random = new FastSourceOfRandomness(randomFile);
GenerationStatus genStatus = new NonTrackingGenerationStatus(random);
....
```
Is this a **Bug** or there is some reason to throw a ``IllegalStateException`` when calling ``readAllBytes()`` of the anonymous ``InputStream`` instance  returned by ``ZestGuidance#getInput()``?

In addition, I also tried to implement this by turning the generated input (through calling ``guidance.getInput()``)  into a ``ByteArrayOutputStream`` to make copies of bytes by repeatly calling ``toByteArray()`` following the resolution plot at SO: https://stackoverflow.com/questions/10329437/reading-from-socket-input-stream-returns-data-in-the-wrong-order.
This implementation is like follows:
```
    // Helper method
    public static ByteArrayOutputStream toByteArrayOutputStream(InputStream input) throws IOException {
        ByteArrayOutputStream baos = new ByteArrayOutputStream();
        byte[] buffer = new byte[1024];
        int len;
        while ((len = input.read(buffer)) > -1) {
            baos.write(buffer, 0, len);
        }
        baos.flush();
        return baos;
    }

    ....
    // Generate input values. Read bytes for copy.
    ByteArrayOutputStream baos = Util.toByteArrayOutputStream(muGuidance.getInput());
    StreamBackedRandom randomFile = new StreamBackedRandom(new ByteArrayInputStream(baos.toByteArray()), Long.BYTES);
    SourceOfRandomness random = new FastSourceOfRandomness(randomFile);
    GenerationStatus genStatus = new NonTrackingGenerationStatus(random);
    ....
```
This implementation will not throw a ``IllegalStatusException``, but it turns out to be undable to find any semantic valid inputs when fuzzing ``CalendarLogic#isLeapYear``, that is, no calendars satisfying "containing a Feb with 29 days" will be generated.

I wander whether there are any better solutions to resolve my requirements? Thank u in advance :-) !

**Comment by QRXqrx** [comment]
...emmm I also trial my second implementation on inputs saved by ``ZestGuidance`` runing with original ``FuzzStatement``. It seems that this implementation will not change inner bytes when working with ``FileInputStream`` and ``BufferedInputStream``. Here is my codes and outputs of running:
```
    @Test
    public void trialCloneInputStream2() throws IOException {
        // Read in initial bytes.
        BufferedInputStream is1 = new BufferedInputStream(new FileInputStream(new File(failuresDirPath, "id_000001")));
        FileInputStream is2 = new FileInputStream(new File(failuresDirPath, "id_000001"));
        ByteArrayOutputStream baos = Util.toByteArrayOutputStream(is2);

        Object[] args1 = genArgs(Collections.singletonList(calGenerator), is1);
        Object[] args2 = genArgs(Collections.singletonList(calGenerator), new ByteArrayInputStream(baos.toByteArray()));
        Object[] args3 = genArgs(Collections.singletonList(calGenerator), new ByteArrayInputStream(baos.toByteArray()));
        check(args1);
        check(args2);
        check(args3);

        Calendar cal1 = (GregorianCalendar) args1[0];
        Calendar cal2 = (GregorianCalendar) args2[0];
        Calendar cal3 = (GregorianCalendar) args3[0];

        String format = "%s: %s-%s\n";
        System.out.printf(format, "cal1", cal1.get(MONTH) + 1, cal1.get(DAY_OF_MONTH));
        System.out.printf(format, "cal2", cal2.get(MONTH) + 1, cal2.get(DAY_OF_MONTH));
        System.out.printf(format, "cal3", cal3.get(MONTH) + 1, cal3.get(DAY_OF_MONTH));
    }

    private void check(Object[] args) {
        assert args.length == 1;
        assert args[0] instanceof GregorianCalendar;
    }
```
outputs:
```
cal1: 2-29
cal2: 2-29
cal3: 2-29
```
I guess there must be some reasons about why the anonymous ``InputStream`` generated by the following code will be changed using ``ByteOutputStream``?
```
    protected InputStream createParameterStream() {
        // Return an input stream that reads bytes from a linear array
        return new InputStream() {
            int bytesRead = 0;

            @Override
            public int read() throws IOException {
                assert currentInput instanceof LinearInput : "ZestGuidance should only mutate LinearInput(s)";

                // For linear inputs, get with key = bytesRead (which is then incremented)
                LinearInput linearInput = (LinearInput) currentInput;
                // Attempt to get a value from the list, or else generate a random value
                int ret = linearInput.getOrGenerateFresh(bytesRead++, random);
                // infoLog("read(%d) = %d", bytesRead, ret);
                return ret;
            }
        };
    }
```

**Comment by rohanpadhye** [comment]
Hello. I see the issue you are running into, and it's sort of a consequence of how bytestreams are handled internally by JQF. The "inputs" to a test are actually not decided ahead of time. Each random choice in the generator is made dynamically by fetching the next few bytes from an input stream. These streams are pseudo-infinite; that is, the only upper bound is a hard-coded limit (see `MAX_INPUT_SIZE`). The actual bytes may be generated lazily, e.g. if a generator returns a lambda that makes random choices on demand by the test application.

ZestGuidance in particular also needs to store each byte that is dynamically generated in the stream, because the stored bytes are subsequently used for mutation----see `LinearInput.fuzz()`, which first copies a linear input using a copy constructor. If you just call `readAllBytes()` or similar on the underlying input stream, all this other logic will get messed up. The same bytes won't be read by Zest and won't be stored properly for subsequent mutation. So, the `IllegalStateException` is not a bug but rather a sanity check to ensure that the stream is not corrupted in this way.

If you want a copy of the input stream, my suggestion is to copy it AFTER the input is fully generated, which often means after the test is executed (since the bytes can be generated dynamically if the generator implements a lazy strategy). The `LinearInput` objects stored by ZestGuidance should have all the information you need in the `values` field.

If you want to make a copy of the input objects generated by Zest (that is, the output of the generator functions), then you can also override the [`Guidance#observeGeneratedArgs`](https://github.com/rohanpadhye/JQF/blob/jqf-1.8/fuzz/src/main/java/edu/berkeley/cs/jqf/fuzz/guidance/Guidance.java#L114-L133) method, which is used to log arguments passed to test methods. The array of args corresponds to the parameters of the test method (in the [calendar example](https://github.com/rohanpadhye/JQF/wiki/Fuzzing-with-Zest#step-2-write-a-test-driver), there will only be one array element of type `List<GregorianCalendar>`).

**Comment by QRXqrx** [comment]
Thanks for your replying! It seems the input stream returned by ``ZestGuidance#getInput()`` stores some bytes should be used after so I cannot do operation with side-effect (like ``readAllBytes()``) to pollute it.

I think my requirement is more like the last approach (the ``Guidance#observeGeneratedArgs``) you mentioned. But there are still some problems. As far as I know, the only ways to implement copying of input objects (specifically the parameter ``args`` needed by ``Guidance#run`` and  ``Guidance#observeGeneratedArgs``) are to (1) utilize ``Object#clone`` or (2) firstly serialize objects into bytes, make copies for these bytes and then deserialize them into objects copies.  However, not all types are ``cloneable`` and ``serializable``. It seems this approach does not work if I want to generify this requirement to other projects/objects under test.

**Comment by rohanpadhye** [comment]
You are right that the only way to copy generated args is via object cloning or bi-serialization, but the classes should support this. You could potentially run the generator again to produce the same input, see the implementation of `ReproGuidance` for how this is done. I still think what you want can be achieved by using the bytes stored in LinearInput. This is how saved inputs/failures are repro'd when using `mvn jqf:repro`, so the mechanism of logging LinearInput bytes and then replaying them as in ReproGuidance should work as expected.

**Comment by QRXqrx** [comment]
>  I still think what you want can be achieved by using the bytes stored in LinearInput. This is how saved inputs/failures are repro'd when using mvn jqf:repro, so the mechanism of logging LinearInput bytes and then replaying them as in ReproGuidance should work as expected.

It does make sense. I will take a look at ``LinearInput`` and ``ReproGuidance``. Thanks a lot.
