### ISSUE TITLE
How to use JQF with maven projects?

### ISSUE THREAD

**Issue by gfarida** [rohanpadhye/JQF#182]
1. I have program which has library in dependency and I want to fuzz method from this library. But I can't understand where I should write pom.xml dependencies for it. Is it in JQF source code? or should I do my own maven project and put in my pom.xml that:
<dependencies>
        <dependency>
            <groupId>edu.berkeley.cs.jqf</groupId>
            <artifactId>jqf-fuzz</artifactId>
            <version>1.7</version>
        </dependency>
    </dependencies>
2. And how do I run fuzz in this case? because I will have .jar file from maven.
Thank you very much for your help!

**Comment by rohanpadhye** [comment]
You just need the JQF jars in your class path. In a maven or gradle
project, adding dependencies in the pom.xml or build.gradle file is the
easiest. If you are running your application some other way, you need to
include all the jars on your classpath there.

I'm not sure I understand your question fully. This is more a generic Java
concept rather than anything specific to JQF.

**Comment by gfarida** [comment]
I want to clarify something. For example I have jar of my project and I want to fuzz it with JQF. I don't want to write all library jars in my classpath and I want to fuzz with jqf+afl. Can I only write jqf dependency in my pom.xml and write @Fuzz annotations in my code and run jqf with this command? jqf/bin/jqf-afl-fuzz -i $AFL_DIR/seeds/ testClass(not main for example) testMethod 
Or should I instrument all jar libraries consist in my program?

**Comment by rohanpadhye** [comment]
Try running the script [`scripts/classpath.sh`](https://github.com/rohanpadhye/JQF/blob/master/scripts/classpath.sh) in the JQF repository, which will output the entire classpath of JQF and all its dependencies. You can use this classpath when compiling your code with the `@Fuzz` annotations using `javac`. 
This classpath is automatically included when you run `bin/jqf-afl-fuzz`. See the tutorial here: https://github.com/rohanpadhye/jqf/wiki/Fuzzing-with-AFL

If you are using Maven for compiling your project that contains the test classes, then putting a dependency only on `jqf-fuzz` should be sufficient, because Maven handles dependency management and will pull all of JQF's libraries for you as well.
