### ISSUE TITLE
Get covered lines from coverage.

### ISSUE THREAD

**Issue by Adian12138** [rohanpadhye/JQF#186]
Hi here,

I have read PR https://github.com/rohanpadhye/JQF/issues/78 and https://github.com/rohanpadhye/JQF/pull/171. I used to  think JQF-implementation is faster than jacoco but it turns to be that jqf-instrumentation record more informations. Does it mean I can get information like the covered line (in format <classname, methodname, linenumber>) using jqf-instrument? If so, what should I do to implement this? It seems that I should implement a ``TraceEventVisitor`` to implement this.

**Comment by sohah** [comment]
Hi, could we get an answer to this question? I am new to JQF and fuzzing in general. What is the best strategy to collect exact coverage of lines of codes? Thanks!

**Comment by rohanpadhye** [comment]
Yes, there are a number of ways to get this, depending on what format you are looking for:

1. Using [`mvn jqf:repro with -DlogCoverage=<file>`](https://github.com/rohanpadhye/JQF/wiki/JQF-Maven-Plugin#flags-only-supported-by-jqfrepro). You can repro any [saved inputs given in the `-Dinput=` argument](https://github.com/rohanpadhye/JQF/wiki/JQF-Maven-Plugin#reproducing-tests). The format of this is JQF's own, so you will figure out how to get the info you are looking for.
2. Run a regular [repro test](https://github.com/rohanpadhye/JQF/wiki/JQF-Maven-Plugin#reproducing-tests) but use your coverage tool, e.g. JaCoCo. If you are already used to collecting coverage from JUnit tests (e.g. via `mvn test` or in an IDE like IntelliJ), then you can simply hardcode the tests to repro using the `@Fuzz(repro=...)` annotation for the fuzz test methods; simply point to the input files or directories which you want to rerun deterministically via `mvn test` or by clicking the "Run" button in IntelliJ.
3. If you want to do this programmatically, then you can extend the `Guidance` (e.g. `ZestGuidance` or `ReproGuidance`) to override the `generateCallback` method, which lets you specify a callback that handles `TraceEvent`s. See the [implementation in ReproGuidance for an example](https://github.com/rohanpadhye/JQF/blob/jqf-1.9/fuzz/src/main/java/edu/berkeley/cs/jqf/fuzz/repro/ReproGuidance.java#L296-L320). If you do this, make sure to still dispatch the callback of the superclass so that you can don't break existing functionality.

**Comment by sohah** [comment]
Great pointers! man thanks.
