### ISSUE TITLE
jqf-afl-fuzz feeds random data instead of afl-mutated samples to the target

### ISSUE THREAD

**Issue by neuracr** [rohanpadhye/jqf#33]
Hello !
I am trying to adapt some existing junit tests to turn them into fuzz-testing with jqf. I tried to code a generator for my data type. For that I used the `SourceOfRandomness random` object to read the data byte per byte with the method `nextBytes`, as you did in [this example](https://github.com/rohanpadhye/jqf/blob/f0979677984bf61e505104fcbda27b442cc561a1/examples/src/main/java/edu/berkeley/cs/jqf/examples/kaitai/KaitaiStream.java#L67). However, I have the feeling that the return values are random and do not depend on the mutated inputs fed by afl.  
I think there is an interface implementation problem between StreamBackedRandom and  SourceOfRandomness.  
[Next bytes](https://github.com/pholser/junit-quickcheck/blob/master/core/src/main/java/com/pholser/junit/quickcheck/random/SourceOfRandomness.java#L118) ask its `delegate` to "generate" the byte. As far as I have understood, the delegate is an instance of [StreamBackedRandom](https://github.com/rohanpadhye/jqf/blob/master/fuzz/src/main/java/edu/berkeley/cs/jqf/fuzz/guidance/StreamBackedRandom.java) and generates data from the input file. But as it does not override the `nextBytes` method, it can't be called from SourceOfRandomness.   
Moreover, I could use [the nextByte method](https://github.com/pholser/junit-quickcheck/blob/master/core/src/main/java/com/pholser/junit/quickcheck/random/SourceOfRandomness.java#L200) but it does not seem to rely on its `delegate` attribute to generate the value, so I can't use it.  
  
To investigate, I tried to log the data fed to the tested method, I wrote to a file the arguments passed the the targeted method during the first dry run of afl, with the `-i` option set and a corpus made of a file full of `aaaaaaaaaaaaa`. I expected to see arguments based on `aaaa...`, but I had different values each time I restarted and they seemed random. This was tried with the DateFormatterTest example.  
  
If you think that's not a bug, how can I build a generator that parses the data fed by afl ?

PS : congrats for this project, I really enjoy the way you approach adapting AFL fuzzing style to java. :+1:

**Comment by rohanpadhye** [comment]
Hello!

I am glad that you have understood the implementation details in such depth. The only thing I can clarify is that when subclassing `java.util.Random`,[ one only has to override the protected `nextByte()` method,](https://docs.oracle.com/javase/10/docs/api/java/util/Random.html#next(int)) since all other public methods such as `nextLong()` or `nextBytes()` internally get their random data from a sequence of calls to `nextByte()`. This is exactly [what StreamBackedRandom does](https://github.com/rohanpadhye/jqf/blob/master/fuzz/src/main/java/edu/berkeley/cs/jqf/fuzz/guidance/StreamBackedRandom.java#L107-L152).

If you would like to verify that there is no indeed no non-determinism in your generator, you can try using the `jqf-repro` tool (see [documentation here](https://github.com/rohanpadhye/jqf/wiki/Fuzzing-with-AFL#analyzing-crashes-and-other-fuzzed-inputs)) to provide a sample test input file and observe what your test does; you can even have it print the input it receives. In AFL-land, this is like simply executing your program with a given test input. Running the `jqf-repro` tool multiple times with the same input file should lead to the same observed behevior; if not, there is something non-deterministic in the generator or test method.

Note that unless you are using the `InputStream` generator, the values you see in your test input may not correspond with the ASCII values you provide in the test input files. That is because the test input files will only be used as a source of random data bytes that are then decoded by your generator. For example, if your test input was a `String`, then the string-generator uses the first few bytes of the input file to determine the length N of the string, and then tries to decode N unicode characters. 

When you run AFL with JQF, you can debug in the following ways: (1) look at the generated corpus/queue directory to make sure AFL picked up your seeds; the first few inputs (from id_000000) should be exactly your seeds, (2) the "stability" values in the AFL status screen should be reasonably high; if the stability is less than around 60%, then there is something wrong*.

*Stability values should ideally be up to 100%, but can sometimes be lower if Java classes perform one-time static initialization (e.g. Apache Tomcat sets up some caches) that is non-reproducible over multiple test runs in the same process.

**Comment by neuracr** [comment]
Hi !
Thanks for your answer! 
I followed your advices and did some tests with [InputStreamGenerator](https://github.com/rohanpadhye/jqf/blob/f0979677984bf61e505104fcbda27b442cc561a1/examples/src/main/java/edu/berkeley/cs/jqf/examples/common/InputStreamGenerator.java) and [ArbitraryLengthStringGenerator](https://github.com/rohanpadhye/jqf/blob/f0979677984bf61e505104fcbda27b442cc561a1/examples/src/main/java/edu/berkeley/cs/jqf/examples/common/ArbitraryLengthStringGenerator.java) that relies on it. Using jqf-repro, I had deterministic behavior and I could also check that the `ArbitraryLengthStringGenerator` generated a string by reading from the input file.  
I think ArbitraryLengthStringGenerator is a super usefull example for someone who wants to create new generators for its own classes.  
I didn't dig deep enough in the SourceOfRandmoness.nextByte(m,M) yesterday but you're right, it all depends on implementing next() method.
