### ISSUE TITLE
JVM issue with code cache

### ISSUE THREAD

**Issue by floyd-fuh** [rohanpadhye/jqf#37]
Hi Rohan,

I'm currently running into an issue:

```
AFL_DIR="/data1/fuzzing/tools/afl-2.52b" /data1/fuzzing/tools/jqf-zip/bin/jqf-afl-showmap  -m 200 -t 30000 -i /data1/fuzzing/documents/test1.txt -c $(/data1/fuzzing/tools/jqf-zip/scripts/examples_classpath.sh) edu.berkeley.cs.jqf.examples.tika.TikaParserTest fuzz
afl-showmap 2.52b by <lcamtuf@google.com>
[*] Executing '/data1/fuzzing/tools/jqf-zip/bin/jqf-afl-target'...

-- Program output begins --
Error occurred during initialization of VM
Could not reserve enough space for code cache
```

I guess that error is from the JVM start in scripts/jqf-driver.sh? I tried to add several JVM options there, for example `-Xmx2000m -Xms2000m -XX:ReservedCodeCacheSize=2048m` but no luck so far. Any idea?

**Comment by rohanpadhye** [comment]
Hi Floyd,

I believe the usage of this script is:
```
Usage: ./bin/jqf-afl-showmap [options] TEST_CLASS TEST_METHOD INPUT_FILE
Options: 
  -c JAVA_CLASSPATH  Classpath used to find your test classes (default is '.')
  -o OUTPUT_FILE     File to write the trace data to (default is 'afl.map')
  -m MEM_LIMIT       Set a memory limit in MB (default is 8192)
  -t TIMEOUT         Set a single-run timeout in milliseconds (default is 10000)
  -v                 Enable verbose logging (in file 'jqf.log')
```

Can you try putting the input file name at the end instead of with an `-i` argument? Also, can you try to provide a larger memory limit using `-m`? That sets an upper bound for AFL (and AFL tools) to spawn processes, including in this case a JVM. The default is far more than the 200MB that you are providing. Does the error persist after these changes?

I am able to get an afl-map dump for Tika using this command (with default memory limit) in the current version.

**Comment by floyd-fuh** [comment]
Oh, you are right! I changed `-i` to the positional argument, but no change. I tried with `-m 2000` but no luck, the error persist.

I think it must be something with the JVM installation on that server (it's a different one as I was using so far), I usually don't have problems running JQF.

But can you confirm that I would need to add arguments to the JVM in the `java -ea ...` invocation in scripts/jqf-driver.sh? I also tried adding `-Xmx2000m -Xms2000m -XX:ReservedCodeCacheSize=2048m` as JVM_OPTS, but no luck so far

**Comment by rohanpadhye** [comment]
That's strange. I see the same error message `Could not reserve enough space for code cache` when I run `jqf-afl-showmap` with a small memory limit, such as `-m 200`. This message is definitely the result of the JVM not being able to initialize with the memory constraints it is given by the execution environment.


> But can you confirm that I would need to add arguments to the JVM in the java -ea ... invocation in scripts/jqf-driver.sh?

You could modify the driver script if you wish, yes. However, simply updating `JVM_OPTS` should be sufficient.

> I also tried adding -Xmx2000m -Xms2000m -XX:ReservedCodeCacheSize=2048m as JVM_OPTS, but no luck so far

Note that giving `-m 2000` to AFL and `-Xms2000m` to the JVM is a bad idea, since the JVM cannot reserve a *minimum heap size* of 2000MB if the upper bound of memory for AFL + JVM + AFL-JVM proxy is 2000MB. You probably want `-m` to be much larger than the actual heap size configured for the JVM. 

Are you able to run `jqf-afl-fuzz` on this same server with the same target? I believe that AFL uses `ulimit` to implement the `-m` option, which may not work if your server/OS is configured to reject such configuration**.

** I don't actually know anything about systems.

**Comment by floyd-fuh** [comment]
So it works now as long as I specify -m none... it's weird, but works for now. Thanks for your help again!
