### ISSUE TITLE
location of perf_tips.txt?

### ISSUE THREAD

**Issue by benedikt90** [rohanpadhye/JQF#68]
This seems trivial, but the fuzzer warns that performance is not great and refers docs/perf_tips.txt. However, I can't find that file. I'm guessing this message needs to be updated? What was the content of the file?

**Comment by rohanpadhye** [comment]
I'm guessing you are getting this message when running AFL as an external tool. This is an AFL-specific message that refers to [this file](https://github.com/google/AFL/blob/master/docs/perf_tips.txt). It is probably not very useful since most of the tips don't apply to JQF. We can't get rid of that message, because it is emitted by AFL. Fuzzing programs in the JVM that use the JDK classes etc. is necessarily slower than fuzzing small C libraries or command-line tools.

For better performance, you can try using the [Zest](https://github.com/rohanpadhye/jqf/wiki/Fuzzing-with-Zest) engine, which can be invoked as a simple [Maven plugin](https://github.com/rohanpadhye/jqf/wiki/JQF-Maven-Plugin).

**Comment by reijin90** [comment]
Oh, that makes sense. Thank you for clearing that up!
