### ISSUE TITLE
Unable to integrate jqf into gradle project

### ISSUE THREAD

**Issue by grankdan** [rohanpadhye/jqf#77]
I'm working on a big proprietary project managed by Gradle and I'm struggling with JQF integration. 
I've tried to rewrite the JQF maven plugin to Gradle plugin+task, but I'm too novice in Gradle to be able to dynamically retract valid class object for GuidedFuzzing. The object I'm getting contain proxy of the `@RunWith` annotation, but the library expects actual annotation class.

I've tried to create simple main class as part of the project where I mimic the implementation of the FuzzGoal, using exact same code but having the java runtime classloader instead of InstrumentingClassLoader. 2 seconds after start of the program I get the message saying 
`Too many trials without coverage; likely all assumption violations`
 which means that no coverage was retrieved from the runs.

Any ideas on how to make JQF work with gradle project?

**Comment by rohanpadhye** [comment]
Hello. I am not personally familiar with Gradle so I cannot give you any Gradle-specific advice.

However, I can confirm that if you replace the `InstrumentingClassLoader` with the Java system classloader, then the loaded classes will not get instrumented. That is likely why you are seeing a warning regarding lack of coverage information.

In order to get coverage info, the bytecode of the application classes must be instrumented as they are loaded. This can be done in one of two ways: (1) Using the `InstrumentingClassLoader`, as done in the Maven plugin, or (2) starting the JVM with a `-javaagent`, as done by the [command-line launch scripts](https://github.com/rohanpadhye/jqf/wiki/Fuzzing-with-Zest).

For Gradle projects, I would recommend the former. The only downside to this is that you cannot instrument classes that have already been loaded before the classloader kicks in, such as Gradle itself and anything that Gradle depends on.

**Comment by vlsi** [comment]
It looks like the most trivial way to use JQF/Zest with Gradle is via ZestCli.

Here are the relevant bits in Kotlin DSL

```kotlin
val zestFuzzerCli by configurations.creating {
    isCanBeConsumed = false
}

dependencies {
    // This it to launch edu.berkeley.cs.jqf.fuzz.ei.ZestCLI
    zestFuzzerCli("edu.berkeley.cs.jqf:jqf-fuzz:1.4-SNAPSHOT")

    // This is to use @Fuzz test annotation
    testImplementation("edu.berkeley.cs.jqf:jqf-fuzz:1.4-SNAPSHOT")
}

val appClasses = sourceSets.main.get().output + sourceSets.test.get().output

val jqfFuzz by tasks.registering(JavaExec::class) {
    main = "edu.berkeley.cs.jqf.fuzz.ei.ZestCLI"
    classpath = zestFuzzerCli
    systemProperty("janala.verbose", "true")
    systemProperty("janala.excludes", "java.,edu.,com.")
    args("--output", "$buildDir/fuzz/$name")
    args("--duration", "5s")
    // This passes the application classes location and the required jars separated with : or ;
    args((configurations.testRuntimeClasspath.get() + appClasses).asPath)
    args("org.apache.calcite.test.fuzzer.JqfFuzzerTest", "hello")
}
```

Note: I pass `--duration 5s` and multiple application jars (see https://github.com/rohanpadhye/jqf/pull/79 ).
