### ISSUE TITLE
Public build of 1.4?

### ISSUE THREAD

**Issue by dsaff** [rohanpadhye/jqf#84]
I see places like https://github.com/rohanpadhye/jqf/issues/77 referring to 1.4-SNAPSHOT.  Is this hosted in a public repo somewhere?

Thanks!

**Comment by rohanpadhye** [comment]
1.4-SNAPSHOT just refers to the latest version (i.e. the head of the master
branch), since the last released version is 1.3. The SNAPSHOT is a rolling
identifier.

I haven't made a 1.4 release yet since there haven't been significant
changes to the fuzzing logic or maven plugin. Most recent changes are
either to the README or to the CLI which you can get by checking out the
latest version of the git repository itself.

Hope that makes sense.

**Comment by dsaff** [comment]
Sure, I understand.  Just one vote here, the specific changes to the CLI (multi-jar classpaths and time limits) were both important to me, so it would justify a 1.4 release in my book, but I know the cost is non-trivial.

Thanks for this package!

**Comment by rohanpadhye** [comment]
Oh, that's good to know. Thanks for the feedback! I'll make a 1.4 release shortly in that case. Keeping this issue open as a reminder.

**Comment by dsaff** [comment]
Just found 1.4.  Thanks so much!

**Comment by rohanpadhye** [comment]
I was waiting to post here until the release propagates to all of Maven Central's servers, but looks like you already found it :-)

Closing this issue as resolved.
