### ISSUE TITLE
have problem about Coverage of maven ，the coverage is  always 0.00%？？

### ISSUE THREAD

**Issue by wuxiaojie555** [rohanpadhye/JQF#91]
I am trying to reproduce the results of the ISSTA'19 paper. I used JQF Maven Plugin to fuzz.
  Run the command:
  mvn jqf:fuzz -Dclass=edu.berkeley.cs.jqf.examples.maven.ModelReaderTest  -Dmethod=testWithGenerator -Dtime=5m.
I don't know why the coverage is  always 0.00%???
       
![image](https://user-images.githubusercontent.com/62991701/79218106-7ca11080-7e82-11ea-9642-2152ec9b718e.png)

**Comment by rohanpadhye** [comment]
You cannot get code coverage for Maven's `ModelReaderTest` when using the JQF Maven plugin. When using the Maven plugin, the Maven classes are already loaded (in order to run the Maven plugin!); so, they cannot be instrumented by JQF. The same goes for JDK classes -- the maven plugin does not instrument standard library classes because they are already loaded by Maven for its own use before JQF even kicks in. JQF can only instrument classes that are loaded dynamically by the test application.

The ISSTA'19 paper was evaluated using command-line scripts such as `bin/jqf-zest`, which perform `premain` instrumentation using a `javaagent`.  This method allows instrumenting almost all classes except those in `java.lang`.

**Comment by wuxiaojie555** [comment]
Thanks for your reply!  I used  scripts bin/jqf-zest to run . 
Run the command:
> path/to/jqf/bin/jqf-zest    -c .:$(path/to/jqf/scripts/classpath.sh):$(path/to/jqf/scripts/examples_classpath.sh)   edu.berkeley.cs.jqf.examples.maven.ModelReaderTest  

I have another question. 
  The the coverage of maven is very low  only about 3.98%??  In the ISSTA'19 paper ,the the coverage of maven is about 15%. How can I get the coverage??
![image](https://user-images.githubusercontent.com/62991701/79334068-361ae700-7f52-11ea-8e50-b26beec1f46a.png)

**Comment by rohanpadhye** [comment]
I'm glad you got the `ModelReaderTest` working!

The percentage on the Zest status screen next to coverage is the fraction of Zest's internal hashmap (which by default is of size 65,536) that is filled up. So, 3.98% is basically 2,606/65,536. If this number gets higher than 50-60%, then you have a high chance of hash collisions and that means you probably want to increase the size of the coverage hash map at the expense of higher instrumentation overhead. These percentages do not reflect the percentage of code covered.

Getting % code coverage automatically is extremely challenging, because Zest has no idea what 100% is. When fuzzing any test case, you are not only running the test application classes, but also usually dozens of other libraries, which depend on more libraries, the JDK, etc. However, the vast majority of this code is not even reachable from the target method that you are fuzzing. So, trying to compute coverage percentage automatically for a *single* fuzzing run is quite meaningless, because there is no ground truth of what an ideal 100% would be.

In the ISSTA'19 paper, we plotted coverage % of semantic branches, by manually identifying the subset of classes in various JARs that correspond to the semantic analysis logic of various benchmarks. Doing this is beyond the scope of the JQF repository, so you won't find it on GitHub. It was a manual process done to satisfy some requirements for the paper itself. Note that those plots would look exactly the same if we had plotted the absolute number of branches on the Y-axis (such as 2,606 in your screenshot), since the percentages scale linearly. You just won't find the denominator on GitHub.

As mentioned in #87, if you are interested in reproducing the results of the ISSTA'19 paper, your best bet is to use the [docker image](https://hub.docker.com/r/rohanpadhye/zest-artifact), which contains a README and scripts to reproduce all experiments, filter out semantic branches, de-duplicate bugs, etc. on exactly that version of JQF+Zest that was used in the paper. It is a reproduction package. The current GitHub repo contains many new changes to JQF+Zest since the paper's publication, so I cannot guarantee that you will get similar results.

Hope this helps.
